# Generated by Django 4.2.2 on 2024-04-03 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_productreview"),
        ("customerauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist_model",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wishes",
                to="products.product",
            ),
        ),
    ]
