# Generated by Django 4.2.2 on 2024-01-12 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0002_addresstype_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="addresstype",
            name="description",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
    ]
