# Generated by Django 4.2.2 on 2024-01-12 20:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0003_remove_addresstype_description_remove_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
