# Generated by Django 4.2.2 on 2024-04-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_status",
            field=models.CharField(
                choices=[
                    ("Preparing", "Preparing"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Returned", "Returned"),
                    ("Lost", "Lost"),
                ],
                default="Preparing",
                max_length=20,
            ),
        ),
    ]
