# Generated by Django 4.2.2 on 2024-01-13 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("customerauth", "0005_alter_address_city_alter_address_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.region",
            ),
        ),
    ]
