# Generated by Django 4.2.2 on 2024-01-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0006_address_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="my_style",
            field=models.BooleanField(default=False),
        ),
    ]
