# Generated by Django 4.2.2 on 2024-04-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0006_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_document",
            field=models.FileField(
                blank=True, null=True, upload_to="billing_documents/"
            ),
        ),
    ]
