# Generated by Django 4.2.2 on 2024-01-15 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("customerauth", "0007_user_my_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyStyles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "home_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.homemodel",
                    ),
                ),
                (
                    "home_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.hometype",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.roomtype",
                    ),
                ),
                (
                    "space_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.spacedefinition",
                    ),
                ),
                (
                    "time_range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.timerange",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
