# Generated by Django 4.2.2 on 2024-01-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("customerauth", "0008_mystyles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mystyles",
            name="home_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.homemodel",
            ),
        ),
        migrations.AlterField(
            model_name="mystyles",
            name="home_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.hometype",
            ),
        ),
        migrations.AlterField(
            model_name="mystyles",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.roomtype",
            ),
        ),
        migrations.AlterField(
            model_name="mystyles",
            name="space_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.spacedefinition",
            ),
        ),
        migrations.AlterField(
            model_name="mystyles",
            name="time_range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.timerange",
            ),
        ),
    ]
