# Generated by Django 4.2.2 on 2024-01-29 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "customerauth",
            "0009_alter_mystyles_home_model_alter_mystyles_home_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_line2",
        ),
    ]
