# Generated by Django 4.2.2 on 2024-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0009_alter_orderitem_rental_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="expired_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
