# Generated by Django 4.2.2 on 2024-01-29 20:04

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0010_remove_address_address_line2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="name",
            new_name="address_name",
        ),
        migrations.RemoveField(
            model_name="address",
            name="state",
        ),
        migrations.AddField(
            model_name="address",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="username",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="usersurname",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
