# Generated by Django 4.2.2 on 2024-04-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0010_orderitem_expired_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_pdf_document",
            field=models.FileField(
                blank=True, null=True, upload_to="order_pdf_documents/"
            ),
        ),
    ]
