# Generated by Django 4.2.2 on 2024-01-30 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0011_rename_name_address_address_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="firm_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="firm_tax_home",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="firm_taxcode",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
