# Generated by Django 4.2.2 on 2024-01-30 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0012_address_firm_name_address_firm_tax_home_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="city",
        ),
    ]
