# Generated by Django 4.2.2 on 2024-04-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0012_order_payment_id_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_transaction_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
