# Generated by Django 4.2.2 on 2024-06-26 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0037_alter_brand_options_alter_category_options_and_more"),
        ("customerauth", "0013_order_payment_transaction_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Siparişler", "verbose_name_plural": "Siparişler"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Sipariş Kalemleri",
                "verbose_name_plural": "Sipariş Kalemleri",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_adress",
            field=models.TextField(verbose_name="Fatura Adresi"),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="billing_documents/",
                verbose_name="Fatura Belgesi",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_adress",
            field=models.TextField(verbose_name="Sipariş Adresi"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_cancel_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sipariş İptal Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_cancel_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Sipariş İptal Nedeni"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_details",
            field=models.TextField(verbose_name="Sipariş Detayları"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Sipariş Numarası"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_pdf_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="order_pdf_documents/",
                verbose_name="Sipariş PDF Belgesi",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Ödeme ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_transaction_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Ödeme İşlem ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_status",
            field=models.CharField(
                choices=[
                    ("Preparing", "Preparing"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Returned", "Returned"),
                    ("Lost", "Lost"),
                ],
                default="Preparing",
                max_length=20,
                verbose_name="Nakliye Durumu",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Toplam Miktar"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="expired_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Son Kullanma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="is_rental",
            field=models.BooleanField(default=False, verbose_name="Kiralık mı"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="customerauth.order",
                verbose_name="Sipariş",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="Ürün",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Miktar"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="rental_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                    ("13", "13"),
                    ("14", "14"),
                    ("15", "15"),
                    ("16", "16"),
                    ("17", "17"),
                    ("18", "18"),
                    ("19", "19"),
                    ("20", "20"),
                    ("21", "21"),
                    ("22", "22"),
                    ("23", "23"),
                    ("24", "24"),
                ],
                max_length=20,
                null=True,
                verbose_name="Kiralama Dönemi",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="rental_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Kiralama Fiyatı",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="selling_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Satış Fiyatı",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi"),
        ),
    ]
