# Generated by Django 4.2.2 on 2024-02-02 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0014_remove_address_country_address_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactus",
            name="phone",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
