# Generated by Django 4.2.2 on 2024-08-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0015_userproductview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userproductview",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="userproductview",
            name="created_date",
        ),
        migrations.AddField(
            model_name="userproductview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
