# Generated by Django 4.2.2 on 2024-09-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0016_alter_userproductview_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
