# Generated by Django 4.2.2 on 2024-09-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0017_user_email_verified_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tckn",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
