# Generated by Django 4.2.2 on 2024-10-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "customerauth",
            "0021_remove_district_city_remove_neighborhood_district_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city_id",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="Şehir ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Şehir Adı")),
            ],
            options={
                "verbose_name": "Şehir",
                "verbose_name_plural": "Şehirler",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Ülke Adı")),
                ("code", models.CharField(max_length=3, verbose_name="Ülke Kodu")),
            ],
            options={
                "verbose_name": "Ülke",
                "verbose_name_plural": "Ülkeler",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district_id",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="İlçe ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="İlçe Adı")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Posta Kodu"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="customerauth.city",
                        to_field="city_id",
                        verbose_name="Şehir",
                    ),
                ),
            ],
            options={
                "verbose_name": "İlçe",
                "verbose_name_plural": "İlçeler",
            },
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "neighborhood_id",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="İlçe ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Mahalle Adı")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Posta Kodu"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighborhood",
                        to="customerauth.district",
                        to_field="district_id",
                        verbose_name="İlçe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahalle",
                "verbose_name_plural": "Mahalleler",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="customerauth.country",
                verbose_name="Ülke",
            ),
        ),
    ]
