# Generated by Django 4.2.2 on 2024-10-12 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0024_order_billing_city_order_billing_neighborhood_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempordercitydata",
            name="billing_city",
        ),
        migrations.RemoveField(
            model_name="tempordercitydata",
            name="billing_neighborhood",
        ),
        migrations.RemoveField(
            model_name="tempordercitydata",
            name="billing_region",
        ),
    ]
