# Generated by Django 4.2.2 on 2024-10-12 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0025_remove_tempordercitydata_billing_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="billing_city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="billing_neighborhood",
        ),
        migrations.RemoveField(
            model_name="order",
            name="billing_region",
        ),
    ]
