# Generated by Django 4.2.2 on 2024-10-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0026_remove_order_billing_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="billing_address",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="order_address",
            field=models.BooleanField(default=False),
        ),
    ]
