# Generated by Django 4.2.2 on 2024-10-13 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0027_address_billing_address_address_order_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="billing_address",
            new_name="billing_addresses",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="order_address",
            new_name="delivery_addresses",
        ),
    ]
