# Generated by Django 4.2.2 on 2024-10-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customerauth",
            "0028_rename_billing_address_address_billing_addresses_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_status",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
    ]
