# Generated by Django 4.2.2 on 2024-10-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0029_remove_order_shipping_status_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_status",
            field=models.CharField(
                default="pending", max_length=20, verbose_name="Kargo Durumu"
            ),
        ),
    ]
