# Generated by Django 4.2.2 on 2024-10-20 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0030_order_shipping_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_status",
        ),
    ]
