# Generated by Django 4.2.2 on 2024-10-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0031_remove_order_shipping_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="neighborhood",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Posta Kodu"
            ),
        ),
    ]
