# Generated by Django 4.2.2 on 2024-01-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="home_banner/"),
                ),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
