# Generated by Django 4.2.2 on 2024-04-03 19:41

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Us",
                "verbose_name_plural": "Contact Us",
            },
        ),
        migrations.CreateModel(
            name="HomeMainBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("subtitle", models.CharField(max_length=1000)),
                (
                    "image",
                    models.ImageField(
                        help_text="The image dimensions must be 1714x584 pixels.",
                        upload_to="banners/",
                        validators=[
                            main.models.validate_image_dimensions,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            ),
                        ],
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("white", "White"),
                            ("black", "Black"),
                        ],
                        default="white",
                        max_length=1000,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("white", "White"),
                            ("black", "Black"),
                        ],
                        default="black",
                        max_length=1000,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "title_position",
                    models.CharField(
                        choices=[
                            ("center", "Center"),
                            ("right", "Right"),
                            ("left", "Left"),
                        ],
                        default="center",
                        max_length=1000,
                    ),
                ),
                (
                    "subtitle_position",
                    models.CharField(
                        choices=[
                            ("center", "Center"),
                            ("right", "Right"),
                            ("left", "Left"),
                        ],
                        default="center",
                        max_length=1000,
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("linkedin", "Linkedin"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
    ]
