# Generated by Django 4.2.2 on 2024-04-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homemainbanner",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
