# Generated by Django 4.2.2 on 2024-04-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_homemainbanner_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homemainbanner",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="homemainbanner",
            name="subtitle_position",
        ),
        migrations.AlterField(
            model_name="homemainbanner",
            name="title_position",
            field=models.CharField(
                choices=[("centerize", "Center"), ("right", "Right"), ("left", "Left")],
                default="center",
                max_length=1000,
            ),
        ),
    ]
