# Generated by Django 4.2.2 on 2024-02-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
