# Generated by Django 4.2.2 on 2024-04-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_homemainbanner_background_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSubBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choose",
                    models.CharField(
                        choices=[
                            ("banner1", "Banner 1"),
                            ("banner2", "Banner 2"),
                            ("banner3", "Banner 3"),
                            ("banner4", "Banner 4"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("subtitle", models.CharField(max_length=1000)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="banners/")),
                ("link", models.CharField(blank=True, max_length=2000, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "text_color",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("white", "White"),
                            ("black", "Black"),
                        ],
                        default="black",
                        max_length=1000,
                    ),
                ),
            ],
        ),
    ]
