# Generated by Django 4.2.2 on 2024-02-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_contactus_is_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("linkedin", "Linkedin"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
    ]
