# Generated by Django 4.2.2 on 2024-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_requesandresponselog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requesandresponselog",
            name="response_status_code",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
