# Generated by Django 4.2.2 on 2024-04-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_teammembers"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembers",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
