# Generated by Django 4.2.2 on 2024-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_teammembers_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembers",
            name="level",
            field=models.IntegerField(
                choices=[
                    (1, "1. Seviye"),
                    (2, "2. Seviye"),
                    (3, "3. Seviye"),
                    (4, "4. Seviye"),
                    (5, "5. Seviye"),
                    (5, "5. Seviye"),
                ],
                default=1,
            ),
        ),
    ]
