# Generated by Django 4.2.2 on 2024-04-30 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_teammembers_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homemainbanner",
            name="image",
            field=models.ImageField(
                help_text="The image dimensions must be 1714x584 pixels.",
                upload_to="banners/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
