# Generated by Django 4.2.2 on 2024-04-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_homemainbanner_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homesubbanner",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
