# Generated by Django 4.2.2 on 2024-04-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_homesubbanner_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homemainbanner",
            name="subtitle",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="homesubbanner",
            name="subtitle",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
