# Generated by Django 4.2.2 on 2024-05-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_homemainbanner_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesandresponselog",
            name="order_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
