# Generated by Django 4.2.2 on 2024-05-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_alter_requesandresponselog_order_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request_Log_Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_data", models.TextField()),
                ("text", models.TextField()),
            ],
        ),
    ]
