# Generated by Django 4.2.2 on 2024-06-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_alter_contactus_options_alter_homemainbanner_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageBannerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200, null=True)),
                ("image", models.ImageField(upload_to="banner_images/")),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("slider", "Slider"),
                        ],
                        default="slider",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name="homesubbanner",
            options={
                "verbose_name": "ÜrünDetay Banner",
                "verbose_name_plural": "Alt Banner",
            },
        ),
    ]
