# Generated by Django 4.2.2 on 2024-06-29 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_homepagebanneritem_alter_homesubbanner_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepagebanneritem",
            options={
                "verbose_name": "Ana Sayfa Banner2",
                "verbose_name_plural": "Ana Sayfa Banner2",
            },
        ),
        migrations.AlterModelOptions(
            name="homesubbanner",
            options={
                "verbose_name": "ÜrünDetay Banner",
                "verbose_name_plural": "ÜrünDetay Banner",
            },
        ),
    ]
