# Generated by Django 4.2.2 on 2024-08-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_alter_homepagebanneritem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
