# Generated by Django 4.2.2 on 2024-08-17 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_contactus_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactUs",
        ),
    ]
