# Generated by Django 4.2.2 on 2024-08-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_delete_contactus"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "İteşim",
                "verbose_name_plural": "İteşim",
            },
        ),
    ]
