# Generated by Django 4.2.2 on 2024-09-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_contactus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="E-Posta Adresi",
                    ),
                ),
            ],
        ),
    ]
