# Generated by Django 4.2.2 on 2024-09-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Abonelik", "verbose_name_plural": "Abonelikler"},
        ),
        migrations.AddField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Kayıt Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Aktif mi?"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="E-Posta Adresi",
            ),
        ),
    ]
