# Generated by Django 4.2.2 on 2024-09-11 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_device"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Device",
        ),
    ]
