# Generated by Django 4.2.2 on 2024-09-24 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_delete_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homemainbanner",
            name="image",
            field=models.ImageField(
                help_text="Resim boyutları 1714x584 piksel olmalıdır.",
                upload_to="banners/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["webp", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
