# Generated by Django 4.2.2 on 2024-10-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_city_country_district_neighborhood_city_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="neighborhood",
            name="district",
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Şehir", "verbose_name_plural": "Şehirler"},
        ),
        migrations.AddField(
            model_name="city",
            name="city_id",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Şehir ID"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Şehir Adı"),
        ),
        migrations.DeleteModel(
            name="District",
        ),
        migrations.DeleteModel(
            name="Neighborhood",
        ),
    ]
