# Generated by Django 4.2.2 on 2024-10-11 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0031_remove_neighborhood_district_alter_city_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="city_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Şehir ID",
            ),
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "district_id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="İlçe ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="İlçe Adı")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Posta Kodu"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="main.city",
                        to_field="city_id",
                        verbose_name="Şehir",
                    ),
                ),
            ],
            options={
                "verbose_name": "İlçe",
                "verbose_name_plural": "İlçeler",
            },
        ),
    ]
