# Generated by Django 4.2.2 on 2024-10-11 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0032_alter_city_city_id_district"),
    ]

    operations = [
        migrations.DeleteModel(
            name="District",
        ),
    ]
