# Generated by Django 4.2.2 on 2024-10-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0034_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "neighborhood_id",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="İlçe ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Mahalle Adı")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Posta Kodu"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighborhood",
                        to="main.district",
                        to_field="district_id",
                        verbose_name="İlçe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahalle",
                "verbose_name_plural": "Mahalleler",
            },
        ),
    ]
