# Generated by Django 4.2.2 on 2024-10-11 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0035_neighborhood"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="district",
            name="city",
        ),
        migrations.RemoveField(
            model_name="neighborhood",
            name="district",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="District",
        ),
        migrations.DeleteModel(
            name="Neighborhood",
        ),
    ]
