# Generated by Django 4.2.2 on 2024-10-20 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customerauth", "0029_remove_order_shipping_status_alter_order_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Alıcı Kodu"
                    ),
                ),
                ("province_name", models.CharField(max_length=100, verbose_name="İl")),
                ("county_name", models.CharField(max_length=100, verbose_name="İlçe")),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Mahalle"
                    ),
                ),
                ("address", models.TextField(verbose_name="Adres")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="TC / Vergi No"
                    ),
                ),
                (
                    "tax_office",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Vergi Dairesi"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Sipariş Numarası"
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(
                        default="KARGOTÜRK", max_length=50, verbose_name="Şube Kodu"
                    ),
                ),
                (
                    "start_branch",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Çıkış Şubesi"
                    ),
                ),
                (
                    "region_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Dağıtım Bölgesi Kodu"
                    ),
                ),
                (
                    "courrier_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Kurye Kodu"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=100, unique=True, verbose_name="Barkod"
                    ),
                ),
                (
                    "sub_barcode",
                    models.TextField(blank=True, verbose_name="Alt Barkod"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tutar",
                    ),
                ),
                (
                    "currency_name",
                    models.CharField(
                        blank=True,
                        default="TRY",
                        max_length=10,
                        verbose_name="Para Birimi",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="İçerik")),
                (
                    "sender_note",
                    models.TextField(blank=True, verbose_name="Gönderici Notu"),
                ),
                (
                    "quantity",
                    models.IntegerField(default=1, verbose_name="Paket Miktar"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ağırlık (Kg)"
                    ),
                ),
                (
                    "total_bulk",
                    models.IntegerField(default=1, verbose_name="Toplam Desi"),
                ),
                (
                    "verification_code",
                    models.CharField(
                        max_length=10, verbose_name="Alıcı Teslim Şifresi"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_orders",
                        to="customerauth.order",
                    ),
                ),
            ],
        ),
    ]
