# Generated by Django 4.2.2 on 2024-10-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingorder",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Müşteri Adı"
            ),
        ),
    ]
