# Generated by Django 4.2.2 on 2024-10-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customerauth", "0030_order_shipping_status"),
        ("shipping", "0003_alter_shippingorder_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_code", models.CharField(max_length=2, unique=True)),
                ("status_description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ShippingMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=50)),
                ("sender_barcode", models.CharField(max_length=50)),
                ("sender_name", models.CharField(max_length=100)),
                ("acceptance_date", models.DateField()),
                ("sender_address", models.TextField()),
                ("sender_city", models.CharField(blank=True, max_length=100)),
                ("sender_phone", models.CharField(blank=True, max_length=15)),
                (
                    "collection_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("weight_bulk", models.DecimalField(decimal_places=2, max_digits=10)),
                ("package_quantity", models.IntegerField()),
                ("recipient_name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("status_number", models.CharField(max_length=10)),
                ("recipient_address", models.TextField()),
                ("recipient_district", models.CharField(max_length=100)),
                ("recipient_city", models.CharField(max_length=100)),
                ("result_status", models.CharField(max_length=50)),
                ("result_description", models.TextField()),
                ("recipient_phone", models.CharField(max_length=15)),
                ("result_date", models.DateField()),
                ("arrival_branch", models.CharField(max_length=100)),
                ("exit_number", models.CharField(max_length=50)),
                ("tracking_url", models.URLField()),
                ("movements", models.JSONField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_movements",
                        to="customerauth.order",
                    ),
                ),
                (
                    "shipping_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_movements",
                        to="shipping.shippingorder",
                    ),
                ),
            ],
        ),
    ]
