# Generated by Django 4.2.2 on 2024-10-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0004_cargostatus_shippingmovement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmovement",
            name="barcode",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="shippingmovement",
            name="exit_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="shippingmovement",
            name="recipient_phone",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="shippingmovement",
            name="sender_barcode",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="shippingmovement",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping.cargostatus",
            ),
        ),
        migrations.AlterField(
            model_name="shippingmovement",
            name="status_number",
            field=models.CharField(max_length=100),
        ),
    ]
