# Generated by Django 4.2.2 on 2024-10-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0008_shippingmovement_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingorder",
            name="branch_code",
            field=models.CharField(
                default="34", max_length=50, verbose_name="Şube Kodu"
            ),
        ),
    ]
