# Generated by Django 4.2.2 on 2024-10-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0009_alter_shippingorder_branch_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingorder",
            name="record_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Kayıt Numarası"
            ),
        ),
    ]
