# Generated by Django 4.2.2 on 2024-10-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0010_shippingorder_record_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingorder",
            name="shipping_status",
            field=models.CharField(
                max_length=4, null=True, verbose_name="Kargo Durumu"
            ),
        ),
    ]
