# Generated by Django 4.2.2 on 2024-10-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0011_alter_shippingorder_shipping_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingorder",
            name="record_id",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Kayıt Numarası"
            ),
        ),
        migrations.AlterField(
            model_name="shippingorder",
            name="shipping_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shipping.cargostatus",
            ),
        ),
    ]
