# Generated by Django 4.2.2 on 2024-10-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0012_alter_shippingorder_record_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingorder",
            name="amount_type_id",
            field=models.IntegerField(default=3, verbose_name="Ödeme Türü"),
        ),
    ]
