# Generated by Django 4.2.2 on 2024-10-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0013_shippingorder_amount_type_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingorder",
            name="shipping_url",
            field=models.URLField(null=True, verbose_name="Kargo Takip Url"),
        ),
    ]
