# Generated by Django 4.2.2 on 2024-02-09 19:41

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="category/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="HomeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="home_models/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="HomeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="home_types/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("in_stock", models.IntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="products.category"
                    ),
                ),
                (
                    "home_models",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="products.homemodel"
                    ),
                ),
                (
                    "home_types",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="products.hometype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="room_types/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpaceDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="space_definitions/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="time_range/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("min_value", models.IntegerField(default=0)),
                ("max_value", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_products",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="room_types",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.roomtype"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="space_definitions",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.spacedefinition"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="time_ranges",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.timerange"
            ),
        ),
    ]
