# Generated by Django 4.2.2 on 2024-02-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="mainImage",
            field=models.ImageField(blank=True, null=True, upload_to="category/"),
        ),
    ]
