# Generated by Django 4.2.2 on 2024-01-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timerange",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="time_range/"),
        ),
    ]
