# Generated by Django 4.2.2 on 2024-02-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_category_mainimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
