# Generated by Django 4.2.2 on 2024-02-19 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_view_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="selling_price",
        ),
        migrations.CreateModel(
            name="ProductRentalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("0-3", "0-3"),
                            ("0-6", "0-6"),
                            ("0-9", "0-6"),
                            ("0-12", "0-12"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("rental_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_products_price",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
