# Generated by Django 4.2.2 on 2024-02-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_rename_price_product_selling_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="selling_old_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="productrentalprice",
            name="rental_old_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
