# Generated by Django 4.2.2 on 2024-03-24 10:51

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_productrentalprice_rental_old_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrentalprice",
            name="name",
            field=models.CharField(
                choices=[
                    ("0-3", "0-3"),
                    ("0-6", "0-6"),
                    ("0-9", "0-9"),
                    ("0-12", "0-12"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="subcategory/"),
                ),
                ("img_alt", models.CharField(max_length=255, unique=True)),
                ("img_title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="products.category",
                    ),
                ),
            ],
        ),
    ]
