# Generated by Django 4.2.2 on 2024-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_productrentalprice_name_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.subcategory"
            ),
        ),
    ]
