# Generated by Django 4.2.2 on 2024-03-25 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_category_options_remove_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
            ),
            preserve_default=False,
        ),
    ]
