# Generated by Django 4.2.2 on 2024-04-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_productreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="img_alt",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="img_title",
            field=models.CharField(max_length=255),
        ),
    ]
