# Generated by Django 4.2.2 on 2024-04-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_alter_productimage_img_alt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="img_alt",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="img_title",
            field=models.CharField(max_length=1000),
        ),
    ]
