# Generated by Django 4.2.2 on 2024-04-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_alter_productimage_img_alt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="information",
            field=models.TextField(blank=True, null=True),
        ),
    ]
