# Generated by Django 4.2.2 on 2024-04-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_product_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="productrentalprice",
            name="discount_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="productrentalprice",
            name="name",
            field=models.CharField(
                choices=[
                    ("1", "1 Ay"),
                    ("2", "2 Ay"),
                    ("3", "3 Ay"),
                    ("4", "4 Ay"),
                    ("5", "5 Ay"),
                    ("6", "6 Ay"),
                    ("7", "7 Ay"),
                    ("8", "8 Ay"),
                    ("9", "9 Ay"),
                    ("10", "10 Ay"),
                    ("11", "11 Ay"),
                    ("12", "12 Ay"),
                    ("18", "18 Ay"),
                    ("24", "24 Ay"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
