# Generated by Django 4.2.2 on 2024-04-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_productrentalprice_discount_rate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productrentalprice",
            old_name="name",
            new_name="month",
        ),
        migrations.RemoveField(
            model_name="productrentalprice",
            name="rental_old_price",
        ),
        migrations.AddField(
            model_name="productrentalprice",
            name="discount_start_month",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
