# Generated by Django 4.2.2 on 2024-04-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_rename_name_productrentalprice_month_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productrentalprice",
            name="discount_rate",
        ),
        migrations.RemoveField(
            model_name="productrentalprice",
            name="discount_start_month",
        ),
        migrations.RemoveField(
            model_name="productrentalprice",
            name="month",
        ),
        migrations.AddField(
            model_name="productrentalprice",
            name="name",
            field=models.CharField(
                choices=[
                    ("0-3", "0-3"),
                    ("0-6", "0-6"),
                    ("0-9", "0-9"),
                    ("0-12", "0-12"),
                ],
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="productrentalprice",
            name="rental_old_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
