# Generated by Django 4.2.2 on 2024-04-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0022_cart_cartitem_cart_items_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="selling_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
