# Generated by Django 4.2.2 on 2024-04-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_alter_cartitem_selling_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrentalprice",
            name="name",
            field=models.CharField(
                choices=[
                    ("1-3", "1-3"),
                    ("4-6", "4-6"),
                    ("7-9", "7-9"),
                    ("10-12", "10-12"),
                    ("13-18", "13-18"),
                    ("19-24", "19-24"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
