# Generated by Django 4.2.2 on 2024-04-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0024_alter_productrentalprice_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="order_completed",
            field=models.BooleanField(default=False),
        ),
    ]
