# Generated by Django 4.2.2 on 2024-04-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0025_cartitem_order_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="order_completed",
            field=models.BooleanField(default=False),
        ),
    ]
