# Generated by Django 4.2.2 on 2024-04-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0027_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="best_seller",
            field=models.BooleanField(default=False),
        ),
    ]
