# Generated by Django 4.2.2 on 2024-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0031_supplier_product_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="img_alt",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="category",
            name="img_title",
            field=models.CharField(max_length=255),
        ),
    ]
