# Generated by Django 4.2.2 on 2024-05-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0032_alter_category_img_alt_alter_category_img_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
