# Generated by Django 4.2.2 on 2024-05-07 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0033_cart_session_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="session_key",
        ),
    ]
