# Generated by Django 4.2.2 on 2024-05-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0034_remove_cart_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
