# Generated by Django 4.2.2 on 2024-06-26 12:17

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0036_alter_cart_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Marka", "verbose_name_plural": "Marka"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Kategoriler",
                "verbose_name_plural": "Kategoiler",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Ürün", "verbose_name_plural": "Ürünler"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Ürün Resimleri",
                "verbose_name_plural": "Ürün Resimleri",
            },
        ),
        migrations.AlterModelOptions(
            name="productrentalprice",
            options={
                "verbose_name": "Ürün Kiralama Fiyatı",
                "verbose_name_plural": "Ürün Kiralama Fiyatı",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Tedarikçi", "verbose_name_plural": "Tedarikçi"},
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Ad"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="rental_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                    ("13", "13"),
                    ("14", "14"),
                    ("15", "15"),
                    ("16", "16"),
                    ("17", "17"),
                    ("18", "18"),
                    ("19", "19"),
                    ("20", "20"),
                    ("21", "21"),
                    ("22", "22"),
                    ("23", "23"),
                    ("24", "24"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category/", verbose_name="Resim"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="img_alt",
            field=models.CharField(max_length=255, verbose_name="Resim Alt Metni"),
        ),
        migrations.AlterField(
            model_name="category",
            name="img_title",
            field=models.CharField(max_length=255, verbose_name="Resim Başlığı"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi"),
        ),
        migrations.AlterField(
            model_name="category",
            name="mainImage",
            field=models.ImageField(
                blank=True, null=True, upload_to="category/", verbose_name="Ana Resim"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Ad"),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.category",
                verbose_name="Üst Kategori",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="best_seller",
            field=models.BooleanField(default=False, verbose_name="En Çok Satılan"),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.brand",
                verbose_name="Marka",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="Kategori",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="product",
            name="home_models",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.homemodel",
                verbose_name="Ev Modelleri",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="home_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.hometype",
                verbose_name="Ev Tipleri",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="in_stock",
            field=models.IntegerField(default=10, verbose_name="Stokta Var"),
        ),
        migrations.AlterField(
            model_name="product",
            name="information",
            field=models.TextField(blank=True, null=True, verbose_name="Bilgi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Öne Çıkan"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="Ad"),
        ),
        migrations.AlterField(
            model_name="product",
            name="room_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.roomtype",
                verbose_name="Oda Tipleri",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_old_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Eski Satış Fiyatı",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Satış Fiyatı"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=50, unique=True, verbose_name="SKU"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="space_definitions",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.spacedefinition",
                verbose_name="Alan Tanımları",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.supplier",
                verbose_name="Tedarikçi",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="time_ranges",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.timerange",
                verbose_name="Zaman Aralıkları",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Görüntülenme Sayısı"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product_images/", verbose_name="Resim"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="img_alt",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Resim Alt Metni"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="img_title",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Resim Başlığı"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_products",
                to="products.product",
                verbose_name="Ürün",
            ),
        ),
        migrations.AlterField(
            model_name="productrentalprice",
            name="name",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                    ("12", "12"),
                    ("13", "13"),
                    ("14", "14"),
                    ("15", "15"),
                    ("16", "16"),
                    ("17", "17"),
                    ("18", "18"),
                    ("19", "19"),
                    ("20", "20"),
                    ("21", "21"),
                    ("22", "22"),
                    ("23", "23"),
                    ("24", "24"),
                ],
                max_length=20,
                null=True,
                verbose_name="Ay",
            ),
        ),
        migrations.AlterField(
            model_name="productrentalprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_products_price",
                to="products.product",
                verbose_name="Ürün",
            ),
        ),
        migrations.AlterField(
            model_name="productrentalprice",
            name="rental_old_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Eski Kiralama Fiyatı",
            ),
        ),
        migrations.AlterField(
            model_name="productrentalprice",
            name="rental_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Kiralama Fiyatı"
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Yorum"),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.product",
                verbose_name="Ürün",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(verbose_name="Puan"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Ad"),
        ),
    ]
