# Generated by Django 4.2.2 on 2024-08-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0039_alter_product_description_alter_product_information_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="related1",
            field=models.ManyToManyField(
                blank=True, related_name="related_product_set", to="products.product"
            ),
        ),
    ]
