# Generated by Django 4.2.2 on 2024-08-18 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0040_product_related1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="related1",
            new_name="related",
        ),
    ]
