# Generated by Django 4.2.2 on 2024-08-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0041_rename_related1_product_related"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="Brand/", verbose_name="Resim"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="img_alt",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Resim Alt Metni"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="img_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Resim Başlığı"
            ),
        ),
    ]
