# Generated by Django 4.2.2 on 2024-08-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0042_brand_image_brand_img_alt_brand_img_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi"),
        ),
    ]
