# Generated by Django 4.2.2 on 2024-08-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0043_brand_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "verbose_name": "Tedarikçi",
                "verbose_name_plural": "Tedarikçiler",
            },
        ),
        migrations.AddField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adres"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Şirket Adı"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Yetkili Kişi"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-Posta Adresi"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="iban",
            field=models.CharField(
                blank=True, max_length=34, null=True, verbose_name="IBAN Numarası"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="invoice_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Fatura Notları"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon Numarası"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="tax_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Vergi Kimlik Numarası (VKN)",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="tax_office",
            field=models.TextField(blank=True, null=True, verbose_name="Vergi Dairesi"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Web Sitesi"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
