# Generated by Django 4.2.2 on 2024-09-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0044_alter_supplier_options_supplier_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="desi",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Desi",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="estimated_delivery_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-2 iş günü", "1-2 iş günü"),
                    ("3-5 iş günü", "3-5 iş günü"),
                    ("5-7 iş günü", "5-7 iş günü"),
                    ("7-10 iş günü", "7-10 iş günü"),
                ],
                default="3-5 iş günü",
                max_length=20,
                null=True,
                verbose_name="Tahmini Teslimat Süresi",
            ),
        ),
    ]
